export enum ProductType {
    GetProduct = 'GETPRODUCT',
    GetProduct_FaiL = 'GETPRODUCT_FAIL',
    GetRecommend = 'GETRECOMMEND',
    GetRecommend_Fail = 'GETRECOMMEND_FAIL',
    GetProductDetail = 'GETPRODUCTDETAIL',
    GetProductDetail_Fail = 'GETPRODUCTDETAIL_FAIL',
    GetProductDetail_Loading = 'GETPRODUCTDETAIL_LOADING',
    CreateProduct = 'CREATEPRODUCT',
    CreateProduct_FaiL = 'CREATEPRODUCT_FAIL',
    CreateProduct_Loading = 'CREATEPRODUCT_LOADING',
    UpdateProduct = 'UPDATEPRODUCT',
    UpdateProduct_FaiL = 'UPDATEPRODUCT_FAIL',
    UpdateProduct_Loading = 'UPDATEPRODUCT_LOADING',
    DeleteProduct = 'DELETEPRODUCT',
    DeleteProduct_FaiL = 'DELETEPRODUCT_FAIL',
    DeleteProduct_Loading = 'DELETEPRODUCT_LOADING',
}
